name: Draft PDF
on:
  push:
    paths:
      - "paper/**"
      - ".github/workflows/draft-pdf.yml"
  pull_request:
    paths:
      - "paper/**"

  workflow_dispatch:        # allow manual runs

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss                  # or 'jose'
          paper-path: paper/paper.md     # <— your subdirectory paper

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # Must be the same directory as the input paper.md
          path: paper/paper.pdf
